import { NavLink, Outlet, useLocation } from 'react-router-dom'
import { BriefcaseBusiness, Building2, FileCheck2, History, LayoutDashboard, LogOut, Network, Settings2, ShieldCheck, Users, Menu, Landmark } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '@/context/AuthContext'
import { Brand, Utility, label } from '@/features/workspace/ui'
export const roleBase = (role?: string) => role==='BIDDER'?'/bidder':role==='AUDITOR'?'/auditor':role==='ADMIN'?'/admin':'/po'
export function AppLayout(){
 const {user,logout}=useAuth(), location=useLocation(), [mobile,setMobile]=useState(false)
 const base=roleBase(user?.role)
 const links=user?.role==='BIDDER'?[[base,'Workspace',LayoutDashboard],[base+'/tenders','Available tenders',BriefcaseBusiness],[base+'/bids','My bids',FileCheck2],[base+'/documents','My documents',Building2],[base+'/profile','Company profile',Settings2]]:user?.role==='ADMIN'?[[base,'Governance',LayoutDashboard],[base+'/tenders','Tenders & rules',BriefcaseBusiness],[base+'/users','Users & roles',Users],[base+'/rules','Rule reliability',Settings2],[base+'/audit','Audit integrity',ShieldCheck]]:user?.role==='AUDITOR'?[[base,'Audit overview',LayoutDashboard],[base+'/queue','Tender records',BriefcaseBusiness],[base+'/audit','Audit trail',History]]:[[base,'Workspace',LayoutDashboard],[base+'/tenders','Tenders',BriefcaseBusiness],[base+'/queue','Verification queue',FileCheck2],[base+'/intelligence','Risk intelligence',Network],[base+'/decisions','Decision desk',ShieldCheck],[base+'/audit','Audit trail',History]]
 return <div className="application"><Utility/><header className="workspace-header"><button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div className="gem-lockup"><Landmark size={26}/><div><strong>GeM <span className="gem-header-divider">/</span> Procurement Workspace</strong><span>Chennai Petroleum Corporation Limited</span></div></div><div className="header-right"><span className="context-label">{user?.role==='BIDDER'?'SELLER':'BUYER'} WORKSPACE</span><span className="avatar">{user?.full_name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span><div><strong>{user?.full_name}</strong><small>{label(user?.role)}</small></div></div></header><aside className={`sidebar ${mobile?'mobile-open':''}`}><div className="sidebar-brand"><Brand/><span>Procurement Compliance Intelligence</span></div><p className="nav-label">{user?.role==='BIDDER'?'SELLER SERVICES':'PROCUREMENT'}</p><nav aria-label="Primary">{links.map(([to,text,Icon])=>{const I=Icon as typeof Users;return <NavLink key={String(to)} to={String(to)} end={String(to)===base} onClick={()=>setMobile(false)} className={({isActive})=>isActive?'nav-link active':'nav-link'}><I size={18}/>{String(text)}</NavLink>})}</nav><div className="sidebar-bottom"><div className="integration-note"><ShieldCheck size={17}/><div><strong>Bidmark verification layer</strong><span>Evidence informs. Officers decide.</span></div></div><button className="nav-link signout" onClick={logout}><LogOut size={17}/>Sign out</button><span className="sidebar-footnote">SIH26100 · Local demonstration</span></div></aside><main id="main" className="workspace-main" key={location.pathname}><Outlet/></main><footer id="accessibility" className="app-footer">Prototype integration concept for GeM · All timestamps in IST · Keyboard navigation supported</footer></div>
}
